name: ci

on:
  push:
    branches: master

jobs:
  # login:
  get-ocir-repository-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: iad.ocir.io
          username: idwwmbyiyhww/ldiaz@fusion.com.ar
          password: "]nK-0q]GGd+jt;h-UVX."
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: iad.ocir.io/idwwmbyiyhww/oracletest:latest