name: ci

on:
  push:
    branches: master

jobs:
  # login:
  get-ocir-repository-test:
    runs-on: ubuntu-latest
    # steps:
    #   -
    #     name: Login to GitHub Container Registry
    #     uses: docker/login-action@v3
    #     with:
    #       registry: iad.ocir.io
    #       username: idwwmbyiyhww/ldiaz@fusion.com.ar
    #       password: "]nK-0q]GGd+jt;h-UVX."
    steps:
      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: oraclelinux
          compartment: "ocid1.compartment.oc1..aaaaaaaaxaicmisivylqal5y5ifobsp4pj64k2lm53uft2pf3z4cisv5vnaq"

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: "]nK-0q]GGd+jt;h-UVX."