name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: iad.ocir.io
          username: idwwmbyiyhww/ldiaz@fusion.com.ar
          password: "]nK-0q]GGd+jt;h-UVX."